# set "USE_CACHE=yes" in travis CI settings to use cache
# set "USE_CACHE=no" to establish the cache

sudo: false
# dist: trusty

addons:
  artifacts:
    debug: true

language: python

cache:
  directories:
    - $HOME/mc
    - $HOME/beam

python:
  - 2.7

branches:
  only:
    - master


before_install:
  - ./travis/before_install.sh
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - ./travis/install.sh

script:
  - ./travis/getbeam.sh
  - ./travis/run-tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
